services:
  typesense:
    image: typesense/typesense:0.23.1
    restart: unless-stopped
    environment:
      TYPESENSE_DATA_DIR: "/data"
      TYPESENSE_API_KEY: "xyz"
    volumes:
      - typesense-data:/data

volumes:
  typesense-data: {}
