version: '3.7'

services:
  node:
    image: node:18-alpine
    working_dir: /app
    command: index
    restart: unless-stopped
    expose:
      - "80"
    ports:
      - "${PORT}:80"
    volumes:
      - ./${VERSION}:/app
