version: '3.7'

services:
  node:
    image: node:16-alpine
    working_dir: /app
    command: [ "node", "index", "${FLAGS}" ]
    restart: always
    ports:
      - "${PORT}:8000"
    volumes:
      - ./${VERSION}:/app
