version: '3.7'

services:
  node:
    image: node:18-alpine
    working_dir: /app
    command: node index
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    volumes:
      - ./${VERSION}:/app
