services:
  redis:
    image: redis:latest
    restart: unless-stopped
    command:
      - sh
      - "-c"
      - redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
